### ISSUE TITLE
Wrong import statement 

### ISSUE THREAD

**Issue by EngineerCoding** [grizzthedj/react-json-to-html#2]
Hi,

Awesome component, it really looks nice! While testing I did find a minor flaw with the docs though, I had to import the component as:

`import {JsonTable} from 'react-json-to-html'`

Instead of 

`import JsonTable from 'react-json-to-html'`

It might be due to changes in how one setups a project (though I doubt that to be honest), so for the record I used the [create-react-app](https://github.com/facebook/create-react-app) command to start my project.

**Comment by grizzthedj** [comment]
Thanks for using this tool!

I think when importing from the module(as you are), you need the curly braces. When importing using a relative path(like in my examples, i.e. `import JsonTable from '../../src/JsonTable';`) you don't need the curly braces. 

For people using the tool, like yourself, you are correct. It should be imported as you have outlined. 

`import {JsonTable} from 'react-json-to-html';`

The `README` has been updated. Thank you for reporting this!
